version: "3.8"
services:
  app:
    container_name: backend-app
    image: backend-image
    build: .
    ports:
      - "2751:8000"
    environment:
      - MONGO_URI=${MONGODB_URL_STRING}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongoDb
    volumes:
      - .:/app
  mongoDb:
    container_name: mongoDb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
